updated workflow

diff --git a/.github/workflows/build_test_push_docker_X86_arm_version_aware.yaml b/.github/workflows/build_test_push_docker_X86_arm_version_aware.yaml
--- a/.github/workflows/build_test_push_docker_X86_arm_version_aware.yaml
+++ b/.github/workflows/build_test_push_docker_X86_arm_version_aware.yaml
@@ -227,14 +227,15 @@ jobs:
           BUILD_FLAGS=$(echo "$BUILD_FLAGS" | sed 's/^ *//')  
           
           cd research_datastream/terraform
-          sed -e "s/\${TAG}/$TAG/g" -e "s/\${BUILD_ARGS}/$BUILD_FLAGS/g" \
-              test/execution_gp_arm_docker_buildNtester.json > test/execution_temp.json
+
+          sed -i -e "s/\${TAG}/$TAG/g" -e "s/\${BUILD_ARGS}/$BUILD_FLAGS/g" \
+            test/execution_gp_arm_docker_buildNtester.json
           
           echo "Generated execution file:"
-          cat test/execution_temp.json
+          cat test/execution_gp_arm_docker_buildNtester.json
           
           echo "Building with TAG: $TAG and FLAGS: $BUILD_FLAGS"
-          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://test/execution_temp.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
+          execution_arn=$(aws stepfunctions start-execution --state-machine-arn $(cat ./sm_ARN.txt) --name docker_builder_$(env TZ=US/Eastern date +'%Y%m%d%H%M%S') --input "file://test/execution_gp_arm_docker_buildNtester.json" --region us-east-1 --query 'executionArn' --output text); echo "Execution ARN: $execution_arn"; status="RUNNING"; while [ "$status" != "SUCCEEDED" ]; do status=$(aws stepfunctions describe-execution --execution-arn "$execution_arn" --region us-east-1 --query 'status' --output text); echo "Current status: $status"; if [ "$status" == "FAILED" ]; then echo "State machine execution failed!"; exit 1; fi; sleep 5; done; echo "State machine execution succeeded!"
 
 
       - name: Tear down infra
